export const FETCH_FPL_DATA_PENDING = 'FETCH_FPL_DATA_PENDING';
export const FETCH_FPL_DATA_SUCCESS = 'FETCH_FPL_DATA_SUCCESS';
export const FETCH_FPL_DATA_ERROR = 'FETCH_FPL_DATA_ERROR';
export const FETCH_PL_TABLE_PENDING = 'FETCH_PL_TABLE_PENDING';
export const FETCH_PL_TABLE_SUCCESS = 'FETCH_PL_TABLE_SUCCESS';
export const FETCH_PL_TABLE_ERROR = 'FETCH_PL_TABLE_ERROR';
